const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('deck', {
  platform: process.platform,
  launch: e => ipcRenderer.invoke('launch', e),
  pickApps: multi => ipcRenderer.invoke('pick-apps', multi),
  appInfo: p => ipcRenderer.invoke('app-info', p),
  locationAvailable: () => ipcRenderer.invoke('location-available'),
  stats: o => ipcRenderer.invoke('stats-get', o),
  sensorStatus: () => ipcRenderer.invoke('sensor-status'),
  installSensors: () => ipcRenderer.invoke('sensor-install'),
  uninstallSensors: () => ipcRenderer.invoke('sensor-uninstall'),
  notify: (t, b) => ipcRenderer.invoke('notify', t, b),
  status: s => ipcRenderer.send('status', s),
  version: () => ipcRenderer.invoke('version'),
  bleReady: () => ipcRenderer.invoke('ble-ready'),
  updateState: () => ipcRenderer.invoke('update-state'),
  checkUpdates: () => ipcRenderer.invoke('update-check'),
  applyUpdate: () => ipcRenderer.invoke('update-apply'),
  updateChannel: on => ipcRenderer.invoke('update-channel', on),
  acknowledgeUpdate: () => ipcRenderer.invoke('update-ack'),
  openUpdateRepo: () => ipcRenderer.invoke('update-repo'),
  onUpdateState: fn => { const listener = (ev, s) => fn(s); ipcRenderer.on('update-state', listener); return () => ipcRenderer.removeListener('update-state', listener); },
  onUpdateOpen: fn => { const listener = () => fn(); ipcRenderer.on('update-open', listener); return () => ipcRenderer.removeListener('update-open', listener); },
  hostState: o => ipcRenderer.invoke('host-state', o),
  mediaArt: key => ipcRenderer.invoke('media-art', key),
  mediaControl: (action, target, options) => ipcRenderer.invoke('media-ctl', action, target, options),
  sysSet: o => ipcRenderer.invoke('sys-set', o),
  pathForFile: f => { try { return webUtils.getPathForFile(f) || ''; } catch (e) { return ''; } }
});
